# Generated by Django 2.2.28 on 2024-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField()),
                ('data', models.DateTimeField()),
                ('http_method', models.CharField(max_length=200)),
                ('URI_request', models.URLField()),
                ('code_answer', models.IntegerField()),
                ('size_answer', models.IntegerField()),
            ],
        ),
    ]
